export const demoProducts = [
  {
    id: "prod-001",
    name: "Crystal Ball Lamp",
    category: "Decor",
    price: 300,
    currency: "INR",
    images: ["assets/images/crystal_ball_lamp.jpg"],
    description: "A charming crystal ball lamp to light up any room.",
    stock_count: 10,
    units_sold: 0,
    total_revenue: 0,
    rating: { avg: 0, count: 0, breakdown: { "5": 0, "4": 0, "3": 0, "2": 0, "1": 0 } },
    reviews: [],
    created_at: "2025-09-28T12:00:00Z"
  },
  {
    id: "prod-002",
    name: "Panda Lamp",
    category: "Decor",
    price: 300,
    currency: "INR",
    images: ["assets/images/panda_lamp.jpg"],
    description: "A cute panda lamp to brighten your nights.",
    stock_count: 10,
    units_sold: 0,
    total_revenue: 0,
    rating: { avg: 0, count: 0, breakdown: { "5": 0, "4": 0, "3": 0, "2": 0, "1": 0 } },
    reviews: [],
    created_at: "2025-09-28T12:00:00Z"
  },
  {
    id: "prod-003",
    name: "Minature Toys",
    category: "Toy",
    price: 100,
    currency: "INR",
    images: ["assets/images/minature_toys.jpg"],
    description: "Small, adorable miniature toys for fun and collection.",
    stock_count: 10,
    units_sold: 0,
    total_revenue: 0,
    rating: { avg: 0, count: 0, breakdown: { "5": 0, "4": 0, "3": 0, "2": 0, "1": 0 } },
    reviews: [],
    created_at: "2025-09-28T12:00:00Z"
  },
  {
    id: "prod-004",
    name: "Night Glowing Minature Toys",
    category: "Toy",
    price: 200,
    currency: "INR",
    images: ["assets/images/night_glowing_minature_toys.jpg"],
    description: "Mini toys that glow at night, perfect for bedtime fun.",
    stock_count: 10,
    units_sold: 0,
    total_revenue: 0,
    rating: { avg: 0, count: 0, breakdown: { "5": 0, "4": 0, "3": 0, "2": 0, "1": 0 } },
    reviews: [],
    created_at: "2025-09-28T12:00:00Z"
  },
  {
    id: "prod-005",
    name: "Glass Message Bottle",
    category: "Decor",
    price: 100,
    currency: "INR",
    images: ["assets/images/glass_message_bottle.jpg"],
    description: "A cute glass bottle for special messages or decor.",
    stock_count: 10,
    units_sold: 0,
    total_revenue: 0,
    rating: { avg: 0, count: 0, breakdown: { "5": 0, "4": 0, "3": 0, "2": 0, "1": 0 } },
    reviews: [],
    created_at: "2025-09-28T12:00:00Z"
  },
  {
    id: "prod-006",
    name: "Night Lamp",
    category: "Decor",
    price: 300,
    currency: "INR",
    images: ["assets/images/night_lamp.jpg"],
    description: "Soft night lamp for cozy evenings.",
    stock_count: 10,
    units_sold: 0,
    total_revenue: 0,
    rating: { avg: 0, count: 0, breakdown: { "5": 0, "4": 0, "3": 0, "2": 0, "1": 0 } },
    reviews: [],
    created_at: "2025-09-28T12:00:00Z"
  },
  {
    id: "prod-007",
    name: "Shin Chan Toys",
    category: "Toy",
    price: 300,
    currency: "INR",
    images: ["assets/images/shin_chan_toys.jpg"],
    description: "Fun Shin Chan themed toys for collectors and kids.",
    stock_count: 10,
    units_sold: 0,
    total_revenue: 0,
    rating: { avg: 0, count: 0, breakdown: { "5": 0, "4": 0, "3": 0, "2": 0, "1": 0 } },
    reviews: [],
    created_at: "2025-09-28T12:00:00Z"
  },
  {
    id: "prod-008",
    name: "Cute Toy Keychains",
    category: "Toy",
    price: 200,
    currency: "INR",
    images: ["assets/images/cute_toy_keychains.jpg"],
    description: "Tiny toy keychains that add charm to your keys or bag.",
    stock_count: 10,
    units_sold: 0,
    total_revenue: 0,
    rating: { avg: 0, count: 0, breakdown: { "5": 0, "4": 0, "3": 0, "2": 0, "1": 0 } },
    reviews: [],
    created_at: "2025-09-28T12:00:00Z"
  }
];
